### ISSUE TITLE
Miss Shiny: Slakoth visor family & Komala (7-6-'24)

### ISSUE THREAD

**Issue by MelkyAir** [Rplus/Pokemon-shiny#377]
Slakoth visor
ID#287

Vigoroth visor
ID#288

Slaking visor
ID#289

Komala
ID#775
https://cdn.jsdelivr.net/gh/PokeMiners/pogo_assets@master/Images/Pokemon%20-%20256x256/Addressable%20Assets/pm775.s.icon.png

Release Date: 7-6-'24
Source: https://pokemongolive.com/post/slumbering-sands-2024?hl=en

images of Slakoth visor family are not yet available.

**Comment by BartmanEH** [comment]
Komala added via PR #378

**Comment by MelkyAir** [comment]
Issue https://github.com/PokeMiners/pogo_assets/issues/97 opened @pokeminers

**Comment by MelkyAir** [comment]
@BartmanEH the images are on discord. Did you have a way to add them as an asset in the Pokeminers Db? Or should we just wait?

**Comment by BartmanEH** [comment]
I made a [PR](https://github.com/PokeMiners/pogo_assets/pull/98) to add them

**Comment by BartmanEH** [comment]
PR #379

**Comment by Evillunte** [comment]
The new slakoth family,is automatically registret as own. without people push on them

**Comment by BartmanEH** [comment]
> The new slakoth family,is automatically registret as own. without people push on them

Hoping this is fixed by PR #382

**Comment by Evillunte** [comment]
> > The new slakoth family,is automatically registret as own. without people push on them
> 
> Hoping this is fixed by PR #382

I have the problem still.
But dont know how fast it usually goes from fix to seeing the fix

**Comment by BartmanEH** [comment]
> I have the problem still. But dont know how fast it usually goes from fix to seeing the fix

The PR hasn't been closed yet. Check the PR tab: https://github.com/Rplus/Pokemon-shiny/pulls

**Comment by BartmanEH** [comment]
@Evillunte try it now, the PR was merged

**Comment by Evillunte** [comment]
Look like et works now. 3 owns are disappeared.
Thx
